apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vks-01-argocd
  namespace: demo-org-ns1-7d7gl
spec:
  topology:
    class: builtin-generic-v3.6.0
    classNamespace: vmware-system-vks-public
    version: v1.35.0---vmware.2-vkr.4
    variables:
      - name: kubernetes
        value:
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: nfs-datastore-policy
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-03a37b547e2e41e3e
    workers:
      machineDeployments:
        - class: node-pool
          name: kubernetes-cluster-4z28-np-qitf
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-03a37b547e2e41e3e
          variables:
            overrides:
              - name: storageClass
                value: vsan-default-storage-policy
